version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5444:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rupikz
      PGDATA: /var/lib/postgresql/data/qgd/local
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d